os: linux
language: elixir
elixir: 1.10.2
otp_release: 22.2.8
cache:
  directories:
    - _build
    - deps
before_install:
  - echo $DEPLOY_KEY_BASE64 | base64 --decode > travis-deploy-key
  - chmod go-rwx travis-deploy-key
  - eval "$(ssh-agent -s)"
  - env SSH_ASKPASS=/bin/true ssh-add travis-deploy-key
  - pip install --user ansible
script:
  - mix test --trace || travis_terminate 1
deploy:
  skip_cleanup: true
  provider: script
  script: ansible-playbook --ssh-extra-args "-o IdentityFile=travis-deploy-key" playbook.yml
  on:
    branch: master
