os: linux
language: elixir
elixir: 1.10.2
otp_release: 22.2.8
cache:
  directories:
    - _build
    - deps
before_install:
  - openssl aes-256-cbc -K $encrypted_a3033ac31b16_key -iv $encrypted_a3033ac31b16_iv -in travis-deploy-key.enc -out ./travis-deploy-key -d
  - chmod go-rwx travis-deploy-key
script:
  - mix test --trace || travis_terminate 1
deploy:
  provider: script
  script: ansible-playbook --ssh-extra-args "-i travis-deploy-key" playbook.yml
  on:
    branch: master
