---
- hosts: localhost
  connection: local
  gather_facts: false

  # run:
  # $ export DO_API_TOKEN=your-token
  # then run this playbook to create droplet
  tasks:
    - digital_ocean_droplet:
        unique_name: yes # "yes" makes it idempotent
        region: ams3 # slug of the region you would like your server to be created in.
        image: debian-10-x64 # slug of the image you would like the droplet created with.
        wait: yes
        name: "bot" # name of the droplet
        size_id: s-1vcpu-1gb # slug of the size you would like the droplet created with.
        state: present
        ssh_keys: ["25655815"] # <----- put your numeric SSH key in here, get it with "doctl compute ssh-key list"
      register: created_droplet

    - digital_ocean_tag:
        name: bot
        resource_id: "{{ created_droplet.data.droplet.id }}"
        state: present
      register: tag_response

    - name: add hosts
      add_host:
        name: "{{ created_droplet.data.ip_address }}"
        groups: "do"

- hosts: do
  remote_user: root
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: wait for port 22 to become available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
      delegate_to: localhost

    - name: gather facts now that host is available
      setup:

    - name: install nginx
      apt:
        name: nginx

    - name: Update all packages
      apt: upgrade=dist update_cache=yes

    - name: copy release
      copy:
        src: ./_build/prod/rel/anybot
        dest: /
